"""Evaluation of parameter sets from real Medis Touch outcomes.

The proposal engine deliberately does not guess how a parameter change would
have affected a historical trade.  That would turn a proposal into a Python
reimplementation of the EA and could create live recommendations from
fabricated evidence.

``OutcomeEvaluator`` therefore requires a caller-provided replay function.
The replay function must run the real Medis Touch decision logic against the
historical bars/data and return outcome-shaped records.  This module only
turns those returned, realized outcomes into the metrics consumed by the
proposal gates.
"""
from __future__ import annotations

import math
from collections.abc import Callable, Iterable, Sequence
from datetime import datetime, timezone
from typing import Any

from .bounds import PARAMETERS
from .candidates import generate_candidates
from .models import Evaluation, ParameterSet, ParameterSpec
from .objective import score_evaluation

RESOLVED_OUTCOMES = frozenset({"win", "loss", "scratch"})
NON_RESOLVED_OUTCOMES = frozenset({"no_fill", "ambiguous"})
VALID_OUTCOMES = RESOLVED_OUTCOMES | NON_RESOLVED_OUTCOMES

OutcomeLoader = Callable[[], Iterable[Any]]
ReplayFunction = Callable[[ParameterSet, Sequence[Any]], Iterable[Any]]


def _field(row: Any, name: str, default: Any = None) -> Any:
    """Read both SQLAlchemy rows and dict/dataclass test records."""
    if isinstance(row, dict):
        return row.get(name, default)
    return getattr(row, name, default)


def _normalise_outcome(value: Any) -> str:
    if hasattr(value, "value"):
        value = value.value
    outcome = str(value).strip().lower()
    if outcome not in VALID_OUTCOMES:
        raise ValueError(
            f"unsupported outcome {value!r}; expected one of {sorted(VALID_OUTCOMES)}"
        )
    return outcome


def _as_timestamp(value: Any) -> datetime | None:
    return value if isinstance(value, datetime) else None


def _resolved_rows(rows: Sequence[Any]) -> list[tuple[Any, str, float]]:
    resolved: list[tuple[Any, str, float]] = []
    for row in rows:
        outcome = _normalise_outcome(_field(row, "outcome"))
        if outcome in NON_RESOLVED_OUTCOMES:
            continue
        realised = _field(row, "realized_r")
        if realised is None or not isinstance(realised, (int, float)) or not math.isfinite(realised):
            signal_id = _field(row, "signal_id", "<unknown>")
            raise ValueError(
                f"resolved outcome {signal_id!r} has no finite realized_r; "
                "do not evaluate proposals with incomplete outcome data"
            )
        resolved.append((row, outcome, float(realised)))
    return resolved


def _max_drawdown(returns: Sequence[float]) -> float:
    equity = peak = drawdown = 0.0
    for realised in returns:
        equity += realised
        peak = max(peak, equity)
        drawdown = max(drawdown, peak - equity)
    return drawdown


def _profit_factor(returns: Sequence[float]) -> float:
    gross_profit = sum(value for value in returns if value > 0)
    gross_loss = -sum(value for value in returns if value < 0)
    if gross_loss:
        return gross_profit / gross_loss
    return math.inf if gross_profit else 0.0


def _expected_shortfall(returns: Sequence[float], tail_fraction: float) -> float:
    tail_size = max(1, math.ceil(len(returns) * tail_fraction))
    return sum(sorted(returns)[:tail_size]) / tail_size


def _bucket_average(rows: Sequence[tuple[Any, str, float]], name: str) -> dict[str, float]:
    buckets: dict[str, list[float]] = {}
    for row, _, realised in rows:
        value = _field(row, name)
        label = str(value) if value not in (None, "") else "UNKNOWN"
        buckets.setdefault(label, []).append(realised)
    return {label: sum(values) / len(values) for label, values in sorted(buckets.items())}


class OutcomeEvaluator:
    """Evaluate candidates using outcomes produced by a real replay.

    ``outcomes`` can be a concrete iterable of historical records or a
    zero-argument loader that fetches a fresh snapshot for each evaluation.
    Records may be ``SignalOutcome`` ORM objects, mappings, or simple
    dataclasses.  The replay callback receives the candidate and the loaded
    records, and must return the outcome records generated by replaying the
    actual EA logic for that candidate.

    No replay callback means no candidate evaluation.  Requiring it is
    intentional: reusing the baseline outcomes for every candidate would
    silently make every proposal look equally valid.
    """

    is_real_outcome_evaluator = True

    def __init__(
        self,
        outcomes: Iterable[Any] | OutcomeLoader,
        replay: ReplayFunction,
        *,
        parameter_specs: dict[str, ParameterSpec] | None = None,
        tail_fraction: float = 0.05,
    ) -> None:
        if not callable(replay):
            raise TypeError("replay must be a callable that runs the real EA decision logic")
        if not 0 < tail_fraction <= 1:
            raise ValueError("tail_fraction must be in (0, 1]")
        if callable(outcomes):
            self._load = outcomes
        else:
            snapshot = tuple(outcomes)
            self._load = lambda: snapshot
        self._replay = replay
        self.parameter_specs = parameter_specs or PARAMETERS
        self.tail_fraction = tail_fraction
        self.replay_backed = True

    def _load_snapshot(self) -> tuple[Any, ...]:
        rows = tuple(self._load())
        if not rows:
            raise ValueError("outcome data is empty; refusing to evaluate a proposal")
        return rows

    def evaluate(self, parameter_set: ParameterSet) -> Evaluation:
        historical = self._load_snapshot()
        replayed = tuple(self._replay(parameter_set, historical))
        if not replayed:
            raise ValueError(
                "EA replay returned no outcomes; refusing to treat missing evidence as a score"
            )
        resolved = _resolved_rows(replayed)
        if not resolved:
            raise ValueError(
                "EA replay returned no resolved outcomes; "
                "no_fill/ambiguous rows cannot produce an expectancy"
            )

        ordered = sorted(
            resolved,
            key=lambda item: _as_timestamp(_field(item[0], "received_at"))
            or datetime.min.replace(tzinfo=timezone.utc),
        )
        returns = [realised for _, _, realised in ordered]
        wins = sum(outcome == "win" for _, outcome, _ in resolved)
        return score_evaluation(
            trades=len(resolved),
            expectancy_r=sum(returns) / len(returns),
            profit_factor=_profit_factor(returns),
            max_drawdown_r=_max_drawdown(returns),
            expected_shortfall_r=_expected_shortfall(returns, self.tail_fraction),
            win_rate=wins / len(resolved),
            # Keep no-fill/ambiguous rows visible in the coverage cost.  A
            # lower value means fewer signals were spent per resolved trade.
            turnover=len(replayed) / len(resolved),
            by_regime=_bucket_average(resolved, "regime"),
            by_session=_bucket_average(resolved, "session"),
            by_symbol=_bucket_average(resolved, "symbol"),
        )

    def evaluate_neighbors(self, parameter_set: ParameterSet) -> Iterable[Evaluation]:
        """Evaluate bounded one-parameter neighbors with the same real replay."""
        for candidate in generate_candidates(parameter_set, self.parameter_specs):
            yield self.evaluate(candidate)